spring.application.name=hw_Spring
movie.data.file=src/main/resources/movies.json
app.rating.threshold=7.0
app.allowed.genres=Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,Film-Noir,\
  History,Horror,Music,Musical,Mystery,Romance,Sci-Fi,Short,Sport,Thriller,War,Western